### ISSUE TITLE
Youtube Video & Playstore not working

### ISSUE THREAD

**Issue by windwst** [shadowsocks/shadowsocks-windows#1018]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
SS-win 3.43

### Environment(Operating system, .NET Framework, etc)
PC: win 10

Android 7.0 ( in WiFi shares SS connection with win10 PC by PAC AutoProxy; this device also has SS-android by madeye in it)

iOS 10.2   ( in WiFi shares SS connection with win10 PC by PAC AutoProxy)

### Steps you have tried

**Youtube

In _only WiFi_ environment:
Android 7.0 is not able to load youtube video in the Youtube app, but all the introduction, users' comments and photo are perfectly loaded. Only the video cannot be played.
iOS 10.2 is able to load youtube video in the Youtebe app. Works Perfectly.

**Playstore
Android 7.0 is not able to download app from Playstore, but all the introduction, users' comments and photo are perfectly loaded. Only app cannot be downloaded.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

In WiFi & SS-android environment:
Android 7.0 is able to load youtube video in the Youtebe app. Works Perfectly.
Android 7.0 is able to download app from Playstore. Works Perfectly.

I have updated the PAC in PC.

But, in my guess, I think the problem is with the PC.

**Comment by celeron533** [comment]
please try to turn on flight mode (airplane mode) then turn it off on your Android phone to flush the DNS cache. If it does not work, make sure the ss-win is in the correct settings and then reboot the Android phone.

**Comment by windwst** [comment]
@celeron533 thx, it works for the problem in YouTube, but not for the download in playstore.

**Comment by celeron533** [comment]
@windwst Interesting...
As far as I know, if you are using a phone manufactured by a Chinese company (such as Huawei) with a modified China mainland version of Android OS, you may encounter this problem. The google service frame is modified because China mainland has no access to Google. A possible solution is to flash you phone to another version of OS, such as European, United States... Note: There are more or less risks to made your phone to brick when flashing the system. Unless you know what you are doing.

**Comment by wongsyrone** [comment]
Disable [protect PAC]
