### ISSUE TITLE
Over kcptun

### ISSUE THREAD

**Issue by jibon57** [shadowsocks/shadowsocks-windows#1107]
Hello,

First of all thanks for all your efforts to make this great application. I would like for a feature that I got in MacOS & Android version but absent in Windows version that is over kcptun. Is it possible to add this feature with windows too?

Thanks

**Comment by asmadeus08** [comment]
No need. Enough to install tcp bbr on server side and all will be working fine. Cause not all ISP allow udp connection and blocking it.

**Comment by wongsyrone** [comment]
KCP is not part of Shadowsocks protocol. Won't fix.

**Comment by celeron533** [comment]
The latest Android version has separated the kcptun from shadowsocks apk and made it as an individual plugin. Due to the limitation of Android system, users are not able to run kcptun and shadowsocks as two individual applications at the same time, so the initial shadowsocks Android version just glue them together.

**Comment by jibon57** [comment]
@wongsyrone But MacOS version is supporting this feature as an optional: https://github.com/shadowsocks/ShadowsocksX-NG . Isn't it possible to add this feature here too? Like it has been added with MacOS version :)

**Comment by celeron533** [comment]
@jibon57 , ss-win should only do its duty to keep the software tiny, robust and agile.
There are some other techniques able to speed-up the network, so let the end-user do the choice by themselves.
For me, I am using KCPtun, too. By written a simple batch file, I could activate the KCPtun by double-click.

PS.
It is strongly recommended that users should do some connectivity critical tests and tweaks before using in production environment rather than 'open box and use'. And I also heard some guys are using radical parameters, which amplifies raw network streams 10 times, just for a better ping delay. This behavior is not encouraged and leads extra pressure on international gateways.

PS2.
Today, WinZip installer file size is about 100MB while 7zip's is less than 2MB. I have not idea what happened with WinZip.

**Comment by asmadeus08** [comment]
Tcp bbr working best and no need on client side. Just do that for Ubuntu x86
wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.10/linux-image-4.10.0-041000-generic_4.10.0-041000.201702191831_i386.deb
dpkg -i linux-image-4.10.0*.deb
dpkg -lgrep linux-image
update-grub
reboot
echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
sysctl -p
sysctl net.ipv4.tcp_available_congestion_control
sysctl net.core.default_qdisc
lsmod | grep bbr
