### ISSUE TITLE
切换服务器或者重启代理导致代理失效

### ISSUE THREAD

**Issue by zhaohaodang** [shadowsocks/shadowsocks-windows#1156]
shadowsocks 4.0.2和4.0.1版本，win7旗舰版，第一次启动软件可以成功代理，但是，每次切换服务器或者重新开启软件，代理就失效了，需要重新启动电脑才能凑效，请问这是什么原因？

**Comment by dyinandy** [comment]
it definitely could reproduce.

This because of the feature of "record user wininet settings and restore after use" will cause use settings lost when Windows Shut down or user logoff.
@wongsyrone  the App should handling the OS shutdown or user logoff event for restore user wininet settings.

**Comment by dyinandy** [comment]
otherwise if user shutdown or logoff the windows when the SSWin working. the OS wininet will keeping current SS settings and lost user's.

**Comment by dyinandy** [comment]
the problem is caused a Windows shut down and user logoff when SS is working.

if user current wininet setting is PROXY_TYPE_AUTO_DETECT .
 |
SS start - enable && global, so wininet is PROXY_TYPE_PROXY  , and save user's ROXY_TYPE_AUTO_DETECT 
 |
Windows shutdown or user logoff. (Wininet keeping PROXY_TYPE_PROXY , and lost saving user's)
 |
Back to Windows and Start up SS again.
 |
SS start -enable && global, the wininet is is PROXY_TYPE_PROXY, and save previous Wininet keeping PROXY_TYPE_PROXY as user record.
 |
SS Exit or Disable, restore user's as PROXY_TYPE_PROXY .
 |
Can't access service anymore.

**Comment by dyinandy** [comment]
@wongsyrone

**Comment by wongsyrone** [comment]
try 816651ebdcaa8571b117864d6fb78cd0a6217362
