### ISSUE TITLE
Internal URLs not accessible in Edge when Shadowsocks in On

### ISSUE THREAD

**Issue by florianmonfort** [shadowsocks/shadowsocks-windows#1237]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
4.0.4.0
### Environment(Operating system, .NET Framework, etc)
Windows 10, latest public build

### Steps you have tried
None?

### What did you expect to see?
Being able to access my company's internal dev addresses which I can already access with Chrome

### What did you see instead?
![image](https://user-images.githubusercontent.com/1446429/28200683-279bf794-68a0-11e7-9dcd-fc4b545f62f3.png)

### Config and error log in detail (with all sensitive info masked)
Going to logs doesn't show anything happening, just "Shadowsocks" started.

For your information when trying to the same URL with Chrome, I can access it. If I turn off Shadowsocks, I can access that URL again too in Edge. It's only when Shadowsocks server is on that it become inaccessible.

**Comment by wongsyrone** [comment]
After system proxy is enabled, Shadowsocks takes care of system-wide proxy settings, and you can check this by executing "sysproxy.exe query". According to your info, you are trying to access internal URL via your Shadowsocks server; it won't work entirely.

**Comment by florianmonfort** [comment]
@wongsyrone how can I solve that?

**Comment by celeron533** [comment]
A simple way may solve this problem.

![image](https://user-images.githubusercontent.com/3608762/28205637-6d25c366-68b5-11e7-85dc-fff2beab4c0b.png)

Or you may need to write a custom PAC file in SS-win folder

**Comment by florianmonfort** [comment]
I already have this:

![image](https://user-images.githubusercontent.com/1446429/28298591-abfe053c-6ba6-11e7-98f4-1cb4624ac16b.png)

Writing my own PAC file? How about a more user friendly solution?

**Comment by celeron533** [comment]
Some of the applications only set the proxy when starting-up. If you already launched the application then change the proxy settings, the application may use out-of-date proxy settings.

**Comment by zslqhua** [comment]
全是英文，看不懂。我也遇到問題：開SSr，使用chrome，插件，愛國。但是，下次開機，沒有運行SSr，發現Edge不能瀏覽國內網頁…在你這個圖片中的界面開關一下，就又能夠打開網頁了！不明白什麼原因，求大神幫忙解答一下，謝謝～

On Jul 18, 2017 10:49, "Florian Monfort" <notifications@github.com> wrote:

I already have this:

[image: image]
<https://user-images.githubusercontent.com/1446429/28298591-abfe053c-6ba6-11e7-98f4-1cb4624ac16b.png>

Writing my own PAC file? How about a more user friendly solution?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shadowsocks/shadowsocks-windows/issues/1237#issuecomment-315942965>,
or mute the thread
