### ISSUE TITLE
win10 开始菜单显示问题

### ISSUE THREAD

**Issue by rqx110** [shadowsocks/shadowsocks-windows#1520]
Shadowsocks在Win10下“固定到开始菜单”时，图标默认背景色为蓝色，和shadowsocks的图标颜色非常接近，造成识别度不高。
解决方式：将附件中Shadowsocks.visualelementsmanifest.xml放于安装目录下，可将背景色修改为黑色。
[Shadowsocks.visualelementsmanifest.zip](https://github.com/shadowsocks/shadowsocks-windows/files/1460407/Shadowsocks.visualelementsmanifest.zip)

**Comment by celeron533** [comment]
和系统主题颜色撞车是个永恒的问题，对所有的app都一样~~~

**Comment by HalfWater** [comment]
回复错误邮件了。
发自网易邮箱大师
在2017年11月19日 12:35，Allen Zhu 写道： Closed #1520.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shadowsocks/shadowsocks-windows","title":"shadowsocks/shadowsocks-windows","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/shadowsocks/shadowsocks-windows"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #1520."}],"action":{"name":"View Issue","url":"https://github.com/shadowsocks/shadowsocks-windows/issues/1520#event-1348636719"}}}
