### ISSUE TITLE
在国家级图书馆不能正常使用的奇怪现象，求分析。

### ISSUE THREAD

**Issue by roro4ever** [shadowsocks/shadowsocks-windows#1592]
服务器：bandwagon，443端口，aes-256-cfb
客户端：win10，ShadowSocks-windows客户端，最新版本
硬件：笔记本、台式机

笔记本在家里和各咖啡馆使用均无任何问题，但只要在某国家级图书馆使用就会出现奇怪的现象。

具体的现象为：某些网站打不开。

比如，我常用的google.co.jp就无法打开，但试了下google.com.hk又可以打开——只是速度比平常慢一些。
可以ping到ss服务器，速度还不错。
SSH也可以连接SS服务器。

但chrome就是无法打开某些网站，以为是switchOmega的规则问题，检查了一下，github同样在规则列表中就可以访问，而列表中的很多网站就不行。

所以甚是奇怪，感觉是图书馆的路由做了什么控制。
有人能解释这种现象吗？

**Comment by shizhao** [comment]
我司的网络也有类似情况。换到firefox下稍微好一点（出现这种状况的频率少一些）。另外，看youtube高清啥的都很流畅，但翻墙开其他网页时常要刷新几次才行

**Comment by Humilton** [comment]
HOST文件没有设置google.co.jp的域名？

**Comment by chenshaoju** [comment]
日志中有什么显示吗？

**Comment by roro4ever** [comment]
@shizhao **如你所说，真的很神奇！**
我装了firefox+switchOmega，然后把chrome的switchOmega的配置导出应用给FF，其他什么都没有动过，居然可以打开google.co.jp了。但跟你一样，需要多刷新几次才行。
这什么鬼，呵呵。  
我开始以为是图书馆的路由器封了443端口，于是下载了一个tcping，ping了我SS服务器的IP+443端口，没有任何问题，可以ping通。
奇怪。

**Comment by roro4ever** [comment]
会不会是浏览器的问题？我用的chrome，以前是从google网站下的，前不久在360中做了一次升级。
但这个现象在升级前是否存在，无法判断。
因为以前没用过图书馆的网络。
难道是升级后变成了和谐版？

**Comment by Lightveil** [comment]
I 


Sent via the Samsung Galaxy Express 3, an AT&T 4G LTE smartphone
-------- Original message --------From: roro <notifications@github.com> Date: 12/29/17  7:08 PM  (GMT-08:00) To: shadowsocks/shadowsocks-windows <shadowsocks-windows@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [shadowsocks/shadowsocks-windows] 在国家级图书馆不能正常使用的奇怪现象，求分析。 (#1592) 

会不会是浏览器的问题？我用的chrome，以前是从google网站下的，前不久在360中做了一次升级。

但这个现象在升级前是否存在，无法判断。

因为以前没用过图书馆的网络。

难道是升级后变成了和谐版？
—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, 
view it on GitHub, or 
mute the thread.






{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shadowsocks/shadowsocks-windows","title":"shadowsocks/shadowsocks-windows","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/shadowsocks/shadowsocks-windows"}},"updates":{"snippets":[{"icon":"PERSON","message":"@roro4ever in #1592: 会不会是浏览器的问题？我用的chrome，以前是从google网站下的，前不久在360中做了一次升级。\r\n但这个现象在升级前是否存在，无法判断。\r\n因为以前没用过图书馆的网络。\r\n难道是升级后变成了和谐版？"}],"action":{"name":"View Issue","url":"https://github.com/shadowsocks/shadowsocks-windows/issues/1592#issuecomment-354524101"}}}

**Comment by zslqhua** [comment]
居然还在使用360！！！

2017年12月30日 11:08，"roro" <notifications@github.com>寫道：

**Comment by celeron533** [comment]
可能部署了深信服之类的

**Comment by roro4ever** [comment]
在VPS上删了SS服务端，换成了SSR，问题解决。
与浏览器无关，看来是图书馆的路由器可以识别SS数据，牛逼了。
