### ISSUE TITLE
System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。 

### ISSUE THREAD

**Issue by zhouhaoo** [shadowsocks/shadowsocks-windows#2320]
### Shadowsocks version / 影梭版本
4.1.5

### Environment(Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
win10

### Steps you have tried / 操作步骤
连不上
重置了ipv4，ipv6.重装软件。换端口，都是无法解决问题。
### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
[2019-04-18 09:44:36] System.Reflection.TargetInvocationException: 操作过程中出现异常，结果无效。 
 有关异常的详细信息，请查看 InnerException。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于意外的数据包格式，握手失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   在 Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by chenshaoju** [comment]
请使用第三方的服务测试服务器的连通性： https://ipcheck.need.sh/

**Comment by zhouhaoo** [comment]
> 请使用第三方的服务测试服务器的连通性：[https](https://ipcheck.need.sh/)：//ipcheck.need.sh/[](https://ipcheck.need.sh/)
试过了 都是通的。手机可以连上，但是电脑不行。

**Comment by chenshaoju** [comment]
手机和电脑在同一个局域网吗？如果是，请尝试重置TCP/IP和Winsock看看：https://github.com/shadowsocks/shadowsocks-windows/issues/2043#issuecomment-430273467

如果同一个局域网不行，但是3G/4G可以，请使用这个第三方小工具测试一下当前网络的连通性：https://github.com/chenshaoju/tcpportcheck/

**Comment by zhouhaoo** [comment]
已重置过TCP/IP和Winsoc，还是不行。
另外小工具测试过，结果是通的。

**Comment by zhouhaoo** [comment]
打开google显示：

此网站无法提供安全连接 www.google.com 发送的响应无效。
尝试运行 Windows 网络诊断。
ERR_SSL_PROTOCOL_ERROR

**Comment by chenshaoju** [comment]
请确保配置正确（IP、端口号、加密方式、密码）。

如果有使用插件，请确保插件的配置也正确。

**Comment by zhouhaoo** [comment]
没使用插件，配置都正确。
会不会是我没服务器没有配置混淆的原因？

**Comment by chenshaoju** [comment]
建议客户端和服务器都套一个插件看看，这样方便调试。

**Comment by koojitso78** [comment]
We have a strange problem in Iran. since 2 or 3 days ago, ShadowSocks in Windows can connect but some sites cannot load; some apps which are blocked here and was working with ShadowSocks, won't connect to ShadowSocks anymore like Spotify and Telegram. There is no error in the server side and there wasn't any update or any change in the server, and I only get an error like this in Windows (System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details...). Android version was working properly, but today it's not working at all. by changing the encryption some sites can load, but apps still are not working. I have to say almost all other VPN protocols that were working perfectly lately, are not working anymore here in Iran since 3 days ago. like L2TP and OpenVPN and now, ShadowSocks.

**Comment by chenshaoju** [comment]
Can you put full log to here? Hide your server IP address plz.

**Comment by koojitso78** [comment]
When I set Telegram/Spotify proxy settings to use 127.0.0.1:1080 the ShadowSocks's client in windows won't give me any error. Also when I set FoxyProxy in Firefox. but when I use Proxifire to use 127.0.0.1:1080, ShadowSocks gives me this error:

System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

also, there isn't any error log in server.

**Comment by koojitso78** [comment]
It's not just a problem of mine, I know several people began having trouble connecting to ShadowSocks with different clients and different servers with different configs since 2 or 3 days ago. Although I'm not sure they are getting this specific error log or something else.

**Comment by chenshaoju** [comment]
This issue looks like your ISP may have a filter for ShadowSocks.
For now, If your server is built by your self, You can add an obfuscation plugin on both sides for fool your ISP:
Kcptun: https://github.com/xtaci/kcptun
Simple-obfs: https://github.com/shadowsocks/simple-obfs
V2Ray-Plugin: https://github.com/shadowsocks/v2ray-plugin
GoQuite: https://github.com/cbeuw/GoQuiet
Cloak: https://github.com/cbeuw/Cloak

**Comment by koojitso78** [comment]
Thank you.
