### ISSUE TITLE
4.1.8.0版本 Google Chrome 链接断开

### ISSUE THREAD

**Issue by EricMzky** [shadowsocks/shadowsocks-windows#2701]
### Shadowsocks version / 影梭版本
4.1.8.0

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
4.6

### Steps you have tried / 操作步骤
正常最新本地PAC

### What did you see instead? / 实际结果
链接GoogleChrome 访问google 经常无反馈 连接失败。

**Comment by chenshaoju** [comment]
SS的日志中有任何显示吗？

**Comment by claford-v-lawrence** [comment]
This has nothing to do with shadowsocks.
If I'm not too much mistaken, this is due to the GFW sniffing ( or possibly spoofing ) your dns queries. I've experienced the same problems on Chrome, but when I use firefox and proxy my dns traffic through socksv5 tunnel, everything still works find. So this is not the problem of shadowsocks. I'd suggest you either switch to firefox ( all hail the great firefox ) or use something like simplednscrypt.
