### ISSUE TITLE
未来是否有增加“plain”加密选项的可能？

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-windows#2882]
关于该加密选项的解释：`plain` (No encryption, just for debugging)
在低性能vps上，能有较好的速度提升

目前隔壁shadowsocks-rust客户端支持该选项，但只有命令行，不如图形客户端方便，故询问

**Comment by chenshaoju** [comment]
可能会实现，无法确定：https://github.com/shadowsocks/shadowsocks-windows/pull/2801#issuecomment-605391503

**Comment by studentmain** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/161 等他们定名字

**Comment by studentmain** [comment]
不过话说回来，你清楚无加密代表什么吗。

**Comment by Aniark** [comment]
> 不过话说回来，你清楚无加密代表什么吗。

套一个tls插件的话，是否解决安全问题？

**Comment by studentmain** [comment]
只能部分解决。密码的另一个作用是用户认证，在无加密的时候用户认证功能也没了。

**Comment by studentmain** [comment]
另外我不觉得跑ss都慢的服务器上跑tls能多快，大家都是chacha20-poly1305和aes-256-gcm，搞不好还都是openssl实现的。

**Comment by Aniark** [comment]
> 另外我不觉得跑ss都慢的服务器上跑tls能多快，大家都是chacha20-poly1305和aes-256-gcm，搞不好还都是openssl实现的。

tls由CF提供，flexible

**Comment by celeron533** [comment]
>另外我不觉得跑ss都慢的服务器上跑tls能多快，大家都是chacha20-poly1305和aes-256-gcm，搞不好还都是openssl实现的。

跑tls有一些好处
1. 混淆
2. 在443端口上发起tls，运营商QoS可能会有缓解
3. CDN协助。可用于加速或者隐藏真实IP（尤其是主机被黑名单的时候依旧保持可用）
4. 结合https反代，甚至可以实现基于源IP和端口综合hash的负载均衡

**Comment by forever8938** [comment]
> 只能部分解决。密码的另一个作用是用户认证，在无加密的时候用户认证功能也没了。

路径就是密码，只要够复杂，不可能被猜中

**Comment by CrazyBoyFeng** [comment]
> > 不过话说回来，你清楚无加密代表什么吗。
> 
> 套一个tls插件的话，是否解决安全问题？

这不就相当于变成v2ray或者trojan了吗？这样的话等于没用上ss。
不过我也觉得使用ss+v2ray_plugin时进行两轮TLS加解密（AEAD也是TLS的算法）十分冗余。不过这带来的速度损耗并不明显，明显的是功耗损失，尤其是在移动设备上。所以楼主这个提议也有意义。在有传输层插件提供安全性的情况下，可以考虑用不安全（但低功耗）的算法做认证，比如table。

**Comment by delphinuz** [comment]
ss-android已有不加密选择，是否windows版也可以加入，谢谢。

**Comment by CrazyBoyFeng** [comment]
> ss-android已有不加密选择，是否windows版也可以加入，谢谢。

下一版接入 ss-rust 就有无加密模式了。不过你现在就可以用上 ss-rust，只是它没有界面，你需要手写配置。

**Comment by database64128** [comment]
Not all encryption methods ss-rust supports will be allowed. We will only allow AEAD ciphers. Not using encryption and stream ciphers will be rejected by the configuration parser.

**Comment by loyess** [comment]
都过这么久了，搞不懂你们为什么还不能统一各平台客户端的加密方式，难道你们社区内部不交流的么？None加密方式用不用，做出来先，把选择权交给用户不好么？

**Comment by database64128** [comment]
@loyess This is a community project. No one is obliged to do anything. We just make contributions we feel like making.

Next time before complaining about your "right of choice", think about how much you've done for the community.

**Comment by loyess** [comment]
得嘞！当我没说。新年happy就是了！

**Comment by CrazyBoyFeng** [comment]
> Not all encryption methods ss-rust supports will be allowed. We will only allow AEAD ciphers. Not using encryption and stream ciphers will be rejected by the configuration parser.

Why is the ss-windows opposed to implementing none cipher? I don't require the project must do so, people with this need can choose ss-rust or v2ray instead. I just wonder the reasons.
Many people who want to use none cipher are actually using v2ray-plugin. When using v2ray-plugin, both encryption and obfuscation are done by it. In this way, the encryption of ss is basically meaningless, unless you want to protect from CDN.
You might say, why not just use v2ray if you only use v2ray-plugin without extra encryption? The reason is that v2ray is too resource-intensive, especially on the mobile devices, which is very power-intensive. Although v2ray-plugin is a derivative project of v2ray, the effect is much better. The reason why I want to use none cipher is the same: to save more computing power. Especially on the mobile devices, the power consumption has dropped significantly when using none cipher.
That is why so many people want to use shadowsocks without shadow.
