### ISSUE TITLE
默认的pac规则不合理，导致部分域名带cn的网站无法访问

### ISSUE THREAD

**Issue by Window-Lee** [shadowsocks/shadowsocks-windows#2998]
默认的pac规则不合理，导致部分域名带cn的网站无法访问。比如cn.pornhub.com。
### 环境
- Shadowsocks客户端版本：4.3.0.0
- 操作系统版本：windows 10

### 操作步骤
手动删除掉pac策略中"@@||cn"一行，问题解决。可以正常访问p站。

### 期望的结果
希望能修改默认的pac策略，使其更合理一些。

**Comment by database64128** [comment]
Please try out the latest build artifacts from #2999: https://ci.appveyor.com/api/buildjobs/20xpk4a3bevcnp8f/artifacts/Shadowsocks-4.2.0.104.zip

Remember to delete `pac.txt` before running the new build.

**Comment by millionart** [comment]
4.3.0.0 同样有此问题，近几个版本pac自从换了来源，总是各种问题不断，连Google.cn都能包含在排除列表了
`  "@@||google.cn",`

**Comment by database64128** [comment]
@millionart Instead of leaving highly subjective and very unhelpful comments/complaints, you should be reading the release notes to learn about the changes we made in each version.

Also, as a side note, `google.cn` is a domain name associated with Chinese servers, and intended to be accessed from Chinese IPs. Therefore, it's included in `geolocation-!cn@cn`, and eventually becomes an exception rule in `pac.txt` by default.

**Comment by GamenRoll** [comment]
xxx**.cn**.xxx.com
xxx.com**.cn**
代码上，请区别对待一下。

**Comment by database64128** [comment]
@GamenRoll https://github.com/shadowsocks/shadowsocks-windows/issues/2998#issuecomment-713737659

**Comment by millionart** [comment]
> @millionart Instead of leaving highly subjective and very unhelpful comments/complaints, you should be reading the release notes to learn about the changes we made in each version.
> 
> Also, as a side note, `google.cn` is a domain name associated with Chinese servers, and intended to be accessed from Chinese IPs. Therefore, it's included in `geolocation-!cn@cn`, and eventually becomes an exception rule in `pac.txt` by default.

Google.cn是中国域名，但在中国不可访问，新版pac对中国用户不友好，请给用户选择pac来源的权力，旧版pac更适合中国用户，谢谢你们一直以来的工作。

**Comment by pluto6496** [comment]
还有默认规则会导致局域网IP也被代理的问题
