### ISSUE TITLE
PAC rule issue for www.gstatic.com

### ISSUE THREAD

**Issue by ziruizhuang** [shadowsocks/shadowsocks-windows#3028]
### Environment

- Shadowsocks client version: 4.3.2.146
- OS version: Windows 10

### Steps you have tried
Tried to use Google Translate website. 
I saw conflicting rules in PAC for "www.gstatic.com", preventing the "www.gstatic.com" being accessed under PAC mode.
Similar issue for "fonts.gstatic.com".

in PAC file:

with "geositePreferDirect": true,
```
(10685 line:)
"|http://www.gstatic.com",
"|https://www.gstatic.com",
...
(16055 line:)
"@@|http://www.gstatic.com",
"@@|https://www.gstatic.com",
```

with "geositePreferDirect": false,
```
(3366 line:)
"@@|http://www.gstatic.com",
"@@|https://www.gstatic.com",
```

either way, traffic of "www.gstatic.com" did not go through remote server. 

Tried whitelisting using user-rule as follows, did not work
```
||gstatic.com^
||www.gstatic.com^
|http://fonts.gstatic.com
|https://fonts.gstatic.com
|http://www.gstatic.com
|https://www.gstatic.com
```

### Possible cause
I am not sure. But from the conflicts shown above, there could be an issue in the logic generating the PAC rules (allowing and forbidding the same URL at the same time).

**Comment by chenshaoju** [comment]
I guess there is some process issue here:
https://github.com/v2fly/domain-list-community/blob/8b75d4c3b750d635f3fc76e859851d9183a57488/data/google#L575

maybe is `full:example.com @cn` ? @database64128

**Comment by database64128** [comment]
The domain names you mentioned have the `cn` tag on them in the geosite database, which means they are marked as having a Chinese access point, which is why they are included in the `geositeDirectGroups` by default so direct connection is used for them.

To work around the issue, simply remove `geolocation:!cn@cn` from `geositeDirectGroups`. Note that we no longer actively maintain the PAC feature. So it's very unlikely any additional measures will be taken.

> But from the conflicts shown above, there could be an issue in the logic generating the PAC rules (allowing and forbidding the same URL at the same time).

This is actually intentional, as exception rules (that we generate from domain names we need direct connection) take precedence over blocking rules (domains that have be accessed from a proxy).

**Comment by database64128** [comment]
I have opened an issue regarding this at the geosite upstream. Hopefully if everyone agrees, the `cn` tag will be removed from these domains.

**Comment by database64128** [comment]
The `cn` attribute has been removed from `gstatic.com` domains. You can now update the geosite database to resolve the issue.
