### ISSUE TITLE
geositePreferDirect does not preserved when switching between proxy modes

### ISSUE THREAD

**Issue by rhwcu** [shadowsocks/shadowsocks-windows#3035]
### Describe the bug

I modified `geositePreferDirect` in `gui-config.json` to `true` using an editor and saved. But after I change proxy mode from PAC to **global** or to **off**, either using shortcut or by clicking the menu, the file is overwritted and the `geositePreferDirect` property is reset to `false`. 

### Environment

- Shadowsocks client version: 4.3.2.146
- OS version: Windwos 10 Enterprise 2004, Insider preview 20241
- .NET version: 4.7.2 (checked from software list)

### Steps you have tried

- Remove and re-download, but problem remains the same.
- Search issues but nothing found.

### What did you expect to see?

The configutation should preserve when switching between proxy modes.

### What did you see instead?

It does not preserve. 

### Config and error log in detail (with all sensitive info masked)

Nothing special, seems ireelavant to this bug. If required, please let me update.

**Comment by database64128** [comment]
Configuration hot reload is not supported. GUI for switching PAC modes will be implemented in version 5. Since version 5 is not coming anytime soon, feel free to implement the feature for the current version in the master branch and open a PR for it. We are more than happy to accept contributions from the community! 😄
