### ISSUE TITLE
Disable share on LAN every time Shadowsocks starts up

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-windows#3054]
**Is your feature request related to a problem? Please describe.**

Currently the setting Share on LAN is persisted across reboot. This is problematic in the following scenario:

1. It was turned on on a laptop and the user forgot to switch it off.
2. The user accidentally connects the laptop to Internet with a public IP.
3. Now the SOCKS5 proxy is exposed on the Internet and could be used to send spam emails, crack passwords, etc.

**Describe the solution you'd like**

Possible solutions:

1. Do not persist share on LAN setting. Reset it every time when it is started.
2. Change the icon of Shadowsocks to explicitly show that share on LAN is enabled.

**Comment by database64128** [comment]
1. Windows Firewall can be easily configured to only allow incoming traffic from the local subnet to reach shadowsocks-windows' local port.
2. I don't think "forgot to turn it off" or "by accident" justifies the proposed change to make the setting not persistent. Users are responsible for their own decisions.
3. Many people (myself included) actually want shadowsocks-Windows to always listen on `0.0.0.0`. This is a valid use case.
4. In version 5, the option will be replaced by a configurable listening address, which will default to loopback address. A user will have to explicitly specify a listening address, instead of simply checking a checkbox. That would give the user more precise control, and hopefully prevent most "accidents".

**Comment by Mygod** [comment]
Counterpoint: it is unreasonable to assume the users are saints that never make mistakes. There is always the trade-off between security and convenience. I think the solution you proposed sounds good, however.

**Comment by zhongweiShao** [comment]
unsubscribe




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shadowsocks/shadowsocks-windows"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月4日(星期一) 中午1:55
收件人:&nbsp;"shadowsocks/shadowsocks-windows"<shadowsocks-windows@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [shadowsocks/shadowsocks-windows] Disable share on LAN every time Shadowsocks starts up (#3054)





 
Counterpoint: it is unreasonable to assume the users are saints that never make mistakes. There is always the trade-off between security and convenience. I think the solution you proposed sounds good, however.

**Comment by chenshaoju** [comment]
@zhongweiShao 不是这么退订的，你需要点击右上角的Unwatch才行。 https://github.com/shadowsocks/shadowsocks-windows
