### ISSUE TITLE
Request for restoring deprecated AEAD stream ciphers such as XChaCha20-Poly1305-IETF

### ISSUE THREAD

**Issue by luminouser** [shadowsocks/shadowsocks-windows#3083]
**Is your feature request related to a problem? Please describe.**
I can't understand why some AEAD ciphers such as XChaCha20-Poly1305-IETF are removed from supported ciphers, just because they include stream ciphers? Come on. You guys may think, according to cryptography textbooks, that block ciphers are more deeply studied and understood than stream ciphers, and stream ciphers are not as reliable as block ciphers. However, XChaCha20-Poly1305-IETF is an AEAD construction, not just a stream cipher. 
There are no clear evidence that AEAD constructions with stream ciphers are not safe. And stream ciphers are usually quicker than block ciphers. Furthermore, XChaCha20-Poly1305-IETF is the officially recommended cipher in libsodium documentation. [read this](https://doc.libsodium.org/secret-key_cryptography/aead#tl-dr-which-one-should-i-use) 

**Describe the solution you'd like**
Restoring the "XChaCha20-Poly1305-IETF" encryption scheme

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by database64128** [comment]
First of all, we didn't remove support for XC20P1305. You can still use XC20P1305 in the latest v4 release, and will still be available in v5. XC20P1305 support is part of our in-house Shadowsocks AEAD implementation. It is secure, and will not be removed.

You may have confused shadowsocks-windows with other implementations like [shadowsocks-rust](https://github.com/shadowsocks/shadowsocks-rust), which didn't implement XC20P1305 in its new crypto library, because XC20P1305 is not in the Shadowsocks AEAD specifications.

About the removal of stream ciphers, it's really not about the _stream ciphers_, but about the way Shadowsocks utilizes stream ciphers, which is [inherently unsecure, and can be easily compromised](https://github.com/edwardz246003/shadowsocks).

The Shadowsocks AEAD protocol, introduced in 2017, is both fast and secure, as proved by multiple benchmarks and audits over the years. There really is no place for the legacy Shadowsocks protocol with stream ciphers to exist anymore.

**Comment by luminouser** [comment]
OK, I'll go to the issue page of shaodowsocks-android and complain about this.

**Comment by luminouser** [comment]
Thank you for your time.
