### ISSUE TITLE
Remove support for RC4 and TABLE

### ISSUE THREAD

**Issue by librehat** [shadowsocks/shadowsocks-windows#335]
They're deprecated for long time enough. Considering there is little usage of these two methods, it's time to remove relevant code.

**Comment by icylogic** [comment]
I agree that RC4 should be removed (and Table, for V2), but I have no idea how many users are using this method. Since removing these code won't bring any actual enhancement for a client, how about warning users for now and removing these code when main versions of server deprecate these methods or when V2 is published ?

@GangZhuo what's your opinion?

**Comment by librehat** [comment]
On the contrary, we should first remove the support in clients. If there are some users using those two methods, they can still use an old client to connect. Then we remove the support in server side which basically means the end of these two methods.

RC4 and TABLE have been warned unsafe for months (if not years).

BTW, RC4 is removed globally in upcoming Fedora 23.

**Comment by GangZhuo** [comment]
I agree that the RC4 and Table should be remove, but I think we should follow the server side.

**Comment by icylogic** [comment]
I remember that @madeye has agreed to remove Table, we may remove these methods together (libev), while other versions of server do not seem to be under development.

**Comment by madeye** [comment]
Yes, I think it's safe to remove these two ciphers.

**Comment by GangZhuo** [comment]
via https://github.com/shadowsocks/shadowsocks-windows/commit/d24548a04f4701dfe9f3e07d6305b5ba3b7a56f8
