### ISSUE TITLE
流量大還是會被牆

### ISSUE THREAD

**Issue by kang000feng** [shadowsocks/shadowsocks-windows#583]
固定一個 TCP/UDP port 流量大還是會被牆，请问使用负载均衡同一个SS服务端开多少个端口可以有效防止被墙？？还是同时开多个SS服务端更有效？多少个合适？

**Comment by chenshaoju** [comment]
请尝试在服务端和客户端启用OTA支持，如果是自己搭建的服务器，请访问： https://github.com/shadowsocks/shadowsocks-libev/blob/master/README.md ，如果是租用的第三方服务，请联系服务商获取支持。

**Comment by kang000feng** [comment]
@chenshaoju 谢谢，OTA是为了对抗CCA攻击，对于gfw这种大流量就干扰的方式有效果吗？大家有用过的说说效果啊。

**Comment by chenshaoju** [comment]
你可以试试，我只能说我自己用的VPS没这个问题。。。

**Comment by kang000feng** [comment]
@chenshaoju 好的，多谢。你的VPS启用OTA支持了吗？对下载速度有影响吗？

**Comment by chenshaoju** [comment]
可能版本不一样，我的是在 /etc/default/shadowsocks ，你可能需要看一下你的 /etc/init.d/shadowsocks 文件中的 Read configuration variable file if it is present 下行的内容和 NAME 的变量。

![unnamed qq screenshot20160602231318](https://cloud.githubusercontent.com/assets/515763/15750081/96f203be-2917-11e6-85ad-ecfcc48f0c3c.png)

![unnamed qq screenshot20160602231024](https://cloud.githubusercontent.com/assets/515763/15749997/32466b76-2917-11e6-98c9-da1cac0c166e.png)

**Comment by Liqianyu** [comment]
我想说OTA是默认开启的。也就是说只要是libev服务端。可以直接开启OTA。服务端开启是强制OTA，不开无法连。

**Comment by chenshaoju** [comment]
@Liqianyu 你换一个端口看看？不要用默认端口。

**Comment by Liqianyu** [comment]
@chenshaoju 什么端口?
https://shadowsocks.org/en/spec/one-time-auth.html

By default, the server that supports OTA should run in the compatible mode. OTA is only applied if the client's request header has a flag set. However, if the server switch on OTA explicitly, all clients must switch on OTA, otherwise connections will be denied.
这段话表明只要服务器支持OTA，客户端直接开启是可以的。服务端如果强制OTA，客户端不开就连不上。

**Comment by chenshaoju** [comment]
@Liqianyu 就是你用的SS服务端端口，目前已知如果是默认的8848（好象是，忘了），可能会被墙。
