### ISSUE TITLE
Support multiple server addresses

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-windows#663]
Could we use a config like this:

    {
      "server": ["2001:abcd::1234", "123.2.33.1"],
      "server_port": 9988,
      "password": "random-key",
      "method": "chacha20",
      "remarks": "",
      "auth": true
    }

It's already supported in libev: https://github.com/shadowsocks/shadowsocks-libev/blob/d319c0300c66c64fe193afd9b3f3253ec668d225/src/jconf.c#L147

**Comment by wongsyrone** [comment]
Then how to input them from UI

**Comment by Mygod** [comment]
If you don't want to create additional UIs, just let user use `,|;/\=+*@` or [whatever character that isn't valid in hostname](https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names). Isn't that obvious?

**Comment by wongsyrone** [comment]
Checking user input is a must-have operation.

**Comment by Mygod** [comment]
*EDIT: ...as delimiter.

**Comment by Noisyfox** [comment]
@wongsyrone any plan on supporting this?

**Comment by Noisyfox** [comment]
Why we need this on the client side?

**Comment by wongsyrone** [comment]
Currently, no plans.

**Comment by Mygod** [comment]
@Noisyfox See my example.

**Comment by Noisyfox** [comment]
I mean this is a feature for server to listen to multiple address.
Why we need this on client? We want to connect to one server with different address?

**Comment by Mygod** [comment]
Yes. As shown in example, a server can have an IPv4 address in addition to an IPv6 address.

**Comment by Noisyfox** [comment]
It's unnecessary and impossible for client to select a proper address for one server. There is no such a policy to tell client which address it should use.
In order to auto detect address usability, you need a statistical process (the client need to connect each address at least once). This will introduce considerable delay for each connection.
Anyway, if you only need to chose a address from ipv4 and ipv6, you just need a simple ping manually. The network situation won't change frequently.

**Comment by Mygod** [comment]
Hmm yeah seems like [shadowsocks-libev is just picking a random one](https://github.com/shadowsocks/shadowsocks-libev/commit/7cf0a95908c815976aa908f34d238ae12d11c69d).
