### ISSUE TITLE
刚刚出现一个运行时错误

### ISSUE THREAD

**Issue by 772807886** [shadowsocks/shadowsocks-windows#664]
![default](https://cloud.githubusercontent.com/assets/10294977/17736240/3d62c6e8-64b9-11e6-8ea3-5634731863c8.PNG)

**Comment by 772807886** [comment]
便携模式，Win 10，14393

**Comment by 772807886** [comment]
版本3.2

**Comment by wongsyrone** [comment]
> although all methods of ConcurrentDictionary<TKey, TValue> are thread-safe, not all methods are atomic, specifically GetOrAdd and AddOrUpdate. 

This might be the root cause.

**Comment by wongsyrone** [comment]
Please test this version: https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows/build/1.0.32/job/nd6t47crxlglbu97/artifacts

**Comment by codexss** [comment]
我也遇到了
![image](https://cloud.githubusercontent.com/assets/5959201/17765722/2d95965e-655a-11e6-9005-34d71c25fc88.png)

**Comment by wongsyrone** [comment]
How about the link I posted above?

**Comment by codexss** [comment]
@wongsyrone 看起来好像是开启负载均衡之后出现的问题……

**Comment by wongsyrone** [comment]
I'm not sure whether I really fix the issue, please test version I posted above.

**Comment by codexss** [comment]
@wongsyrone 上面那个版本也有这个问题

**Comment by wongsyrone** [comment]
What's your .NET version?

**Comment by codexss** [comment]
.net 4.0 win10 x64

Syrone Wong <notifications@github.com>于2016年8月18日周四 19:36写道：

**Comment by Noisyfox** [comment]
I think it may be caused by the fact that "_lastInboundCounter" and "_lastOutboundCounter" are not guaranteed to be updated in pairs (They are updated separately at [here](https://github.com/shadowsocks/shadowsocks-windows/blob/a1eef6eac1499ad9baf985bb5d6fa3a6c2b4246c/shadowsocks-csharp/Controller/Service/TCPRelay.cs#L556) and [here](https://github.com/shadowsocks/shadowsocks-windows/blob/a1eef6eac1499ad9baf985bb5d6fa3a6c2b4246c/shadowsocks-csharp/Controller/Service/TCPRelay.cs#L628)). 
So it may happen that a new server was added into "_lastInboundCounter" but not in "_lastOutboundCounter", then the program will fall at [this line](https://github.com/shadowsocks/shadowsocks-windows/blob/a1eef6eac1499ad9baf985bb5d6fa3a6c2b4246c/shadowsocks-csharp/Controller/Service/AvailabilityStatistics.cs#L117) with a KeyNotFoundException.

**Comment by Noisyfox** [comment]
Or "_inboundCounter" and "_outboundCounter" because of the same reason.

**Comment by rebiu** [comment]
![default](https://cloud.githubusercontent.com/assets/13211387/17797884/1242793a-65ff-11e6-8abe-1a53341e7c95.PNG)

win 10 x64 最新版本，系统自带杀毒软件，ss 便携模式， 3.2之后的测试版都有几率出现这样的错误
然后ss_privoxy会关闭的

日志

[2016-08-19 11:17:39] System.ComponentModel.Win32Exception (0x80004005): 32 位进程无法访问 64 位进程的模块。
   在 System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   在 System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   在 System.Diagnostics.Process.get_MainModule()
   在 Shadowsocks.Controller.PolipoRunner.IsChildProcess(Process process)
   在 System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   在 Shadowsocks.Controller.PolipoRunner.Start(Configuration configuration)
   在 Shadowsocks.Controller.ShadowsocksController.Reload()

**Comment by wongsyrone** [comment]
@rebiu open another issue

**Comment by Noisyfox** [comment]
That doesn't make sense. ss_privoxy is definitely a x86 process.
@rebiu Did you run some other x64 version of ss_privoxy on your computer?

**Comment by rebiu** [comment]
@Noisyfox 
No , only use ss define ,no other proxy

**Comment by 772807886** [comment]
@wongsyrone 上面的那个版本我试用了一天，问题并没有重现。而我换回之前的版本，一天下来，问题也没有重现。
现在我不能确定问题重现的时机。应该是有随机性的。
上面提到了说是负载均衡的问题，我一直使用的是负载均衡模式，一直处于这个模式，但也只出现了一次这个问题。

**Comment by Noisyfox** [comment]
@rebiu 
try this version
https://ci.appveyor.com/project/icylogic/shadowsocks-windows-l9mwe/build/job/ro9v8mnnfdf51a92/artifacts

**Comment by wongsyrone** [comment]
Test latest AppVeyor version.
