### ISSUE TITLE
Switching too frequently when using Load Balancing or High Availability mode

### ISSUE THREAD

**Issue by xbb123** [shadowsocks/shadowsocks-windows#861]
Please read Wiki carefully, especially https://github.com/shadowsocks/shadowsocks-windows/wiki/Troubleshooting.
Please answer these questions before submitting your issue. Thanks!

### Version(release version or AppVeyor link)
3.3.4

### Environment(Operating system, .NET Framework, etc)
Windows 10 1607

### Steps you have tried
Choosing  Load Balancing or High Availability mode given that lots of servers are available in the server list. 

### What did you expect to see?
When a server is functional, no switching should be done; or allow users to adjust settings for server switching threshold for a given host.
For example, if a.com was visited using server A the first time, then the second attempt should also be made using server A (if server A is still online)
### What did you see instead?
Server switching very frequently, causing websites with IP-Session binding to logout automatically. 

### Config and error log in detail (with all sensitive info masked)
N/A

Thanks for your work.

**Comment by Noisyfox** [comment]
Well load balancing means choosing server randomly so you are not supposed to use this mode with ip sensitive website.

It does make sense to use same server for some website, however if we implement this feature, we'll need to make a configuration form since not every websites are ip sensitive and that's is a great deal of work.

As a workaround, you may open two ss, one is load balancing and the other is normal mode, then use SwitchyOmega to make those ip sensitive websites work.

**Comment by xbb123** [comment]
Load balancing should be balance traffic whenever possible. 
Your idea of using two instances was brilliant, but a bit complicated. 
Using same sever does not necessarily need to keep a list of websites thats IP sensitive. We can always store the server used for a host and keep using it until server status is changed.

**Comment by Noisyfox** [comment]
Then if I open a lot of pages from the same website which is not IP sensitive, all traffic will go through the same server, which, in all means, is not 'balancing'.

**Comment by xbb123** [comment]
Considering the very feature of balancing, you have to assume that all the requests were properly balanced the first time they were sent. In this case, you don't need to “rebalance” them.
On Nov 7, 2016 10:20, Noisyfox <notifications@github.com> wrote:Then if I open a lot of pages from the same website which is not IP sensitive, all traffic will go through the same server, which, in all means, is not 'balancing'.

**Comment by xbb123** [comment]
If you opened lots of pages in same host, then yes, traffic may not be so balanced. This is a trade-off you have to make. Most of the users may not realize not-balanced-traffic, but they will notice if they've been log outed frequently.

**Comment by icylogic** [comment]
I've implemented a strategy in which the choice is kept for an interval. It's not perfect for this problem, but by setting a longer interval, this problem should happen less frequently.

In fact, I think "balance" in this software is quite different from its original meaning. And random scheduling is somehow meaningless when the key resource is the connection between the "balancing server" (user's desktop) and other servers. 
The point should be making ONE good choice rather than making many choices. In this case, I think you should choose other suitable strategies or design a better one. You may not need to write code, and a good idea posted as an issue should help.

**Comment by Noisyfox** [comment]
Well, let's discuss these here #499
